# flowable 配置
flowable:
  # 关闭异步，不关闭历史数据的插入就是异步的，会在同一个事物里面，无法回滚
  # 开发可开启会提高些效率，上线需要关闭
  async-executor-activate: false

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/flowable?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&failOverReadOnly=false
    hikari:
      maximum-pool-size: 100
      maxIdle: 20
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci

